from . import res_config_settings
from . import teixo
from . import center
from . import partner
from . import purchase
from . import invoice
from . import sale
from . import operation
from . import collection
from . import bill_of_lading
